**Row Echelon Form**

In [50]:
import numpy as np
import sympy as sp
np.random.seed(6)
A = np.random.randint(0,10,(5,5))
print(A)

[[9 3 4 0 9]
 [1 9 1 4 1]
 [8 2 4 2 5]
 [9 6 2 5 5]
 [1 4 5 0 2]]


In [51]:
A=sp.Matrix(A)
A

Matrix([
[9, 3, 4, 0, 9],
[1, 9, 1, 4, 1],
[8, 2, 4, 2, 5],
[9, 6, 2, 5, 5],
[1, 4, 5, 0, 2]])

In [52]:
A[1:2,0:5]=9*A[1:2,0:5]-A[0:1,0:5]
A

Matrix([
[9,  3, 4,  0, 9],
[0, 78, 5, 36, 0],
[8,  2, 4,  2, 5],
[9,  6, 2,  5, 5],
[1,  4, 5,  0, 2]])

In [53]:
A[2:3,0:5]=9*A[2:3,0:5]-8*A[0:1,0:5]
A

Matrix([
[9,  3, 4,  0,   9],
[0, 78, 5, 36,   0],
[0, -6, 4, 18, -27],
[9,  6, 2,  5,   5],
[1,  4, 5,  0,   2]])

In [54]:
A[3:4,0:5]=A[3:4,0:5]-A[0:1,0:5]
A

Matrix([
[9,  3,  4,  0,   9],
[0, 78,  5, 36,   0],
[0, -6,  4, 18, -27],
[0,  3, -2,  5,  -4],
[1,  4,  5,  0,   2]])

In [55]:
A[4:5,0:5]=9*A[4:5,0:5]-A[0:1,0:5]
A

Matrix([
[9,  3,  4,  0,   9],
[0, 78,  5, 36,   0],
[0, -6,  4, 18, -27],
[0,  3, -2,  5,  -4],
[0, 33, 41,  0,   9]])

In [56]:
A[2:3,0:5]=78*A[2:3,0:5]+6*A[1:2,0:5]
A

Matrix([
[9,  3,   4,    0,     9],
[0, 78,   5,   36,     0],
[0,  0, 342, 1620, -2106],
[0,  3,  -2,    5,    -4],
[0, 33,  41,    0,     9]])

In [57]:
A[3:4,0:5]=78*A[3:4,0:5]-3*A[1:2,0:5]
A

Matrix([
[9,  3,    4,    0,     9],
[0, 78,    5,   36,     0],
[0,  0,  342, 1620, -2106],
[0,  0, -171,  282,  -312],
[0, 33,   41,    0,     9]])

In [58]:
A[4:5,0:5]=78*A[4:5,0:5]-33*A[1:2,0:5]
A

Matrix([
[9,  3,    4,     0,     9],
[0, 78,    5,    36,     0],
[0,  0,  342,  1620, -2106],
[0,  0, -171,   282,  -312],
[0,  0, 3033, -1188,   702]])

In [59]:
A[3:4,0:5]=342*A[3:4,0:5]+171*A[2:3,0:5]
A

Matrix([
[9,  3,    4,      0,       9],
[0, 78,    5,     36,       0],
[0,  0,  342,   1620,   -2106],
[0,  0,    0, 373464, -466830],
[0,  0, 3033,  -1188,     702]])

In [60]:
A[4:5,0:5]=342*A[4:5,0:5]-3033*A[2:3,0:5]
A

Matrix([
[9,  3,   4,        0,       9],
[0, 78,   5,       36,       0],
[0,  0, 342,     1620,   -2106],
[0,  0,   0,   373464, -466830],
[0,  0,   0, -5319756, 6627582]])

In [61]:
A[4:5,0:5]=373464*A[4:5,0:5]+5319756*A[3:4,0:5]
A

Matrix([
[9,  3,   4,      0,           9],
[0, 78,   5,     36,           0],
[0,  0, 342,   1620,       -2106],
[0,  0,   0, 373464,     -466830],
[0,  0,   0,      0, -8258409432]])