**SVD** **Decomposition**

In [3]:
import numpy as np
import sympy as sp
np.random.seed(6)
A = np.random.randint(0,10,(5,5))
print(A)

[[9 3 4 0 9]
 [1 9 1 4 1]
 [8 2 4 2 5]
 [9 6 2 5 5]
 [1 4 5 0 2]]


In [4]:
sp.Matrix(A)

Matrix([
[9, 3, 4, 0, 9],
[1, 9, 1, 4, 1],
[8, 2, 4, 2, 5],
[9, 6, 2, 5, 5],
[1, 4, 5, 0, 2]])

In [5]:
U,S,Vt=np.linalg.svd(A)
sp.Matrix(np.round(U))

Matrix([
[-1.0,    0,    0, -1.0,    0],
[   0, -1.0,    0,    0,    0],
[   0,    0,    0,  1.0, -1.0],
[-1.0,    0, -1.0,    0,  1.0],
[   0,    0,  1.0,    0,    0]])

In [10]:
sp.Matrix(U)

Matrix([
[-0.580219066352003,   0.43197177776287,  0.231179166749316, -0.650616566181264, -0.000703512323333576],
[-0.278177836817813,  -0.82627553261251, 0.0353110228147489, -0.287546670453895,     -0.39491249573536],
[-0.461238589606887,  0.256857749729317, -0.040245312923446,  0.568251708927458,     -0.62988361619442],
[-0.570236624234252, -0.172284112166233, -0.532285541001728,  0.204404522548141,     0.565720134942519],
[-0.219207851101064, -0.187113357410377,  0.812626446872768,  0.359616160071084,      0.35672255991588]])

In [11]:
sp.Matrix(Vt)

Matrix([
[ -0.65513477867915, -0.426426851264703, -0.300978099900382, -0.220146132570479, -0.499906417222373],
[ 0.356646631562264, -0.782083953824934,  0.068497733976923, -0.385584986853572,   0.32829886950461],
[-0.414945352759924,  0.187646226319949,  0.721525786953337, -0.494114645241077,  0.166914661101045],
[ 0.229448498634881, -0.281345115002441,  0.605798279336892,  0.384210634282013, -0.594633455160014],
[ 0.467734265002526,  0.303543488980037, -0.130878674100141, -0.641165192513044, -0.510748447100794]])

In [7]:
Sigma=np.zeros((A.shape[0],A.shape[1]))

In [8]:
Sigma[:A.shape[1],:A.shape[0]]=np.diag(S)
sp.Matrix(Sigma)

Matrix([
[22.196036744329,                0,                0,                0,                 0],
[              0, 9.47341653945084,                0,                0,                 0],
[              0,                0, 5.26330126954175,                0,                 0],
[              0,                0,                0, 2.62444414289667,                 0],
[              0,                0,                0,                0, 0.016870130730725]])

In [15]:
U1=U[:,:2]
U1=sp.Matrix(U1)
U1

Matrix([
[-0.580219066352003,   0.43197177776287],
[-0.278177836817813,  -0.82627553261251],
[-0.461238589606887,  0.256857749729317],
[-0.570236624234252, -0.172284112166233],
[-0.219207851101064, -0.187113357410377]])

In [16]:
Vt1=Vt[:2,:]
Vt1=sp.Matrix(Vt1)
Vt1

Matrix([
[-0.65513477867915, -0.426426851264703, -0.300978099900382, -0.220146132570479, -0.499906417222373],
[0.356646631562264, -0.782083953824934,  0.068497733976923, -0.385584986853572,   0.32829886950461]])

In [17]:
Sig1=Sigma[:2,:2]
Sig1=sp.Matrix(Sig1)
Sig1

Matrix([
[22.196036744329,                0],
[              0, 9.47341653945084]])

In [19]:
A2=U1@Sig1@Vt1
print('Rank 2 Aproximation of A')
A2

Rank 2 Aproximation of A


Matrix([
[9.89668166313211, 2.29128342180654, 4.15647539171763, 1.25725637877544,  7.78155723036068],
[1.25338815320509, 8.75483060496993, 1.32219642606634, 4.37750550278692, 0.516835522061125],
[7.57488835034235, 2.46255593867026, 3.24799100474176, 1.31553133157345,  5.91673262631509],
[7.70994655013731, 6.67373590291119, 3.69768125911374, 3.41570871707106,  5.79148918130219],
[2.55539527713573, 3.46112344150211, 1.34300337157354, 1.75462004619859,  1.85037394051619]])

In [20]:
U2=U[:,:3]
U2=sp.Matrix(U1)
U2

Matrix([
[-0.580219066352003,   0.43197177776287],
[-0.278177836817813,  -0.82627553261251],
[-0.461238589606887,  0.256857749729317],
[-0.570236624234252, -0.172284112166233],
[-0.219207851101064, -0.187113357410377]])

In [21]:
Vt2=Vt[:3,:]
Vt2=sp.Matrix(Vt2)
Vt2

Matrix([
[ -0.65513477867915, -0.426426851264703, -0.300978099900382, -0.220146132570479, -0.499906417222373],
[ 0.356646631562264, -0.782083953824934,  0.068497733976923, -0.385584986853572,   0.32829886950461],
[-0.414945352759924,  0.187646226319949,  0.721525786953337, -0.494114645241077,  0.166914661101045]])

In [22]:
Sig2=Sigma[:3,:3]
Sig2=sp.Matrix(Sig2)
Sig2

Matrix([
[22.196036744329,                0,                0],
[              0, 9.47341653945084,                0],
[              0,                0, 5.26330126954175]])

In [23]:
A3=U1@Sig1@Vt1
print('Rank 3 Aproximation of A')
A3

Rank 3 Aproximation of A


Matrix([
[9.89668166313211, 2.29128342180654, 4.15647539171763, 1.25725637877544,  7.78155723036068],
[1.25338815320509, 8.75483060496993, 1.32219642606634, 4.37750550278692, 0.516835522061125],
[7.57488835034235, 2.46255593867026, 3.24799100474176, 1.31553133157345,  5.91673262631509],
[7.70994655013731, 6.67373590291119, 3.69768125911374, 3.41570871707106,  5.79148918130219],
[2.55539527713573, 3.46112344150211, 1.34300337157354, 1.75462004619859,  1.85037394051619]])